apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sans-pulp/pi-homelab-gitops.git
    targetRevision: main
    path: manifests/whoami
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true        # delete resources when removed from Git
      selfHeal: true     # revert manual changes
    syncOptions:
    - CreateNamespace=true
